version: '3.8'


services:
  mysql:
    image: mysql:5.7
#    restart: always
#    volumes:
#      - ./mysql/conf:/etc/mysql/conf.d
#      - ./mysql/db.sql:/docker-entrypoint-initdb.d/db.sql
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notify
    ports:
      - "3306:3306"
    networks:
      my_network:
        ipv4_address: 172.20.0.2

  notify-api:
    restart: always
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - mysql
    networks:
      my_network:
        ipv4_address: 172.20.0.3

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
volumes:
  db_data:

#  docker-compose down
#  docker-compose up --build -d