// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"notify/notify-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/WSNotice",
				Handler: WSNoticeHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/deleteNotice",
				Handler: deleteNoticeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/getNoticeList",
				Handler: getNoticeListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/loginIn",
				Handler: loginInHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/setNotice",
				Handler: setNoticeHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/updateNotice",
				Handler: updateNoticeHandler(serverCtx),
			},
		},
	)
}
